import React from 'react';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'devSik 블로그',
  description: 'Generated by create next app',
  keywords: '블로그, 제품, 키워드',
  robots: 'INDEX, FOLLOW',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={sans.className}>
      {/* <meta name="naver-site-verification" content="a0f90629cc177872e597b95fe41df907956e5dff" /> */}
      <body className="flex flex-col w-full max-w-screen-2xl mx-auto">
        <Header />
        <main className="grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
